# Generated by Django 3.2.10 on 2024-04-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PenziApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='phone_number',
        ),
    ]
