# Generated by Django 3.2.10 on 2024-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PenziApi', '0002_rename_sender_messages_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
