# Generated by Django 5.0.4 on 2024-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="messages",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=100)),
                ("receipient", models.CharField(max_length=100)),
                ("message_txt", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("county", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                ("level_of_edu", models.CharField(max_length=100)),
                ("profesion", models.CharField(max_length=100)),
                ("marital_stat", models.CharField(max_length=100)),
                ("religion", models.CharField(max_length=100)),
                ("ethnicity", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
