# Generated by Django 5.0.4 on 2024-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=100)),
                ("receipient", models.CharField(max_length=100)),
                ("message_txt", models.TextField()),
                ("response", models.CharField(blank=True, max_length=255, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("county", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                (
                    "level_of_edu",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("profesion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "marital_stat",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                ("ethnicity", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
