# Generated by Django 5.0.4 on 2024-04-24 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PenziApi", "0002_message_receivedmessage_user_userdescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
